name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: "./.github/actions/win32deps"

      - name: Build & Distribute (SigDigger)
        run: |
          cd Scripts
          chmod a+x dist-mingw32.sh
          BUILDTYPE=Release BRANCH=master ./dist-mingw32.sh
          cd ..

      - name: Archive .ZIP files
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest-zip
          path: Scripts/SigDigger-*.zip
